### ISSUE TITLE
3주차 진행 계획

### ISSUE THREAD

**Issue by HongJungKim-dev** [CodeSoom/project-react-3-HongJungKim-dev#13]
1. 이 앱을 언제 사용하나요?
   음식 취향에 대한 질문에 답해서 오늘의 메뉴를 정하고 싶을때 이용할 수 있습니다.

2. 구체적인 사례는 무엇인가요?
   사용자는 음식 취향에 대한 여러 질문들에 대한 답을 합니다. 
   여러 선택지 중에서 대답할 수 있습니다.   
   답변을 완료하면 오늘의 메뉴를 추천합니다.
   결과 페이지에서 버튼을 눌러 유사한 음식을 다시 추천받을 수 있습니다.

3. 이번주가 지나면 사용자는 무엇을 할 수 있나요?
   * 질문페이지의 디자인을 보면서 쉽게 선택지를 답할 수 있습니다.
 
4. 이번주에 구현할 기능을 우선 순위대로 작성해 주세요.
   * github pages배포 오류 해결하여 사용자가 구현 상황을 확인할 수 있습니다.
   * README.md를 수정하여 사용자가 이것이 어떤 프로젝트인지, 만들려고하는 의도가 무엇인지, 어떻게 사용하는지, 배포주소가 무엇인지 알 수 있습니다.
   * 질문들을 추가하여 사용자가 다양한 질문을 볼 수 있습니다.
   * 질문페이지의 데이터를 실제데이터로 수정하여 기획한 선택지들을 사용자가 답할 수 있습니다.
   * 질문페이지의 디자인을 추가하여 사용자가 쉽게 이해하면서 선택지를 고를 수 있습니다.

**Comment by HongJungKim-dev** [comment]
기획파트 1명, 디자인파트 1명을 대학생으로 구해서 같이 회의를 했습니다.
회의결과 기존의 여행테스트는 자신의 성향을 드러내는 결과를 내지 않는 이상 공유가 일어나는게 크지 않을것이라고 판단했습니다. 그래서 재미있으면서도 더 많은 사용자가 사용할만한 서비스를 고민하던중 컨셉을 변경하기로 했습니다.
기존에 mbti테스트를 통한 여행지 추천이었다면 여러 질문을 통한 결과로 오늘의 메뉴를 추천해주는 서비스입니다.

2주차 진행계획에도 있는 내용이지만 기존과 컨셉이 달라져서 다시 말씀드립니다.

**Comment by Kihyun92** [comment]
팀을 꾸리셨군요 👍🏼  

기획이 변경된만큼, 매주 주말까지 유저에게 어떻게하면 가치를 전달할 수 있을지에 집중해보시면 좋을 것 같아요 :)
